### ISSUE TITLE
Broken build with 7.1

### ISSUE THREAD

**Issue by remicollet** [jedisct1/libsodium-php#191]
During build

```
BUILDSTDERR: /builddir/build/BUILD/php-pecl-libsodium2-2.0.17/ZTS/libsodium.c: In function 'sodium_exception_create_object':
BUILDSTDERR: /builddir/build/BUILD/php-pecl-libsodium2-2.0.17/ZTS/libsodium.c:416:16: warning: implicit declaration of function 'ZVAL_EMPTY_ARRAY'; did you mean 'ZVAL_EMPTY_STRING'
? [-Wimplicit-function-declaration]
BUILDSTDERR:                 ZVAL_EMPTY_ARRAY(args);
BUILDSTDERR:                 ^~~~~~~~~~~~~~~~
BUILDSTDERR:                 ZVAL_EMPTY_STRING

```
Runtime:

`BUILDSTDERR: PHP Warning:  PHP Startup: Unable to load dynamic library '/builddir/build/BUILDROOT/php-pecl-libsodium2-2.0.17-1.fc27.remi.7.1.x86_64/usr/lib64/php/modules/sodium.so' - /builddir/build/BUILDROOT/php-pecl-libsodium2-2.0.17-1.fc27.remi.7.1.x86_64/usr/lib64/php/modules/sodium.so: undefined symbol: ZVAL_EMPTY_ARRAY in Unknown on line 0
`
